### ISSUE TITLE
output formatting

### ISSUE THREAD

**Issue by MrPiada** [MrPiada/ChessRepertoireGenerator#12]
Example of the actual output:

```
(1m49s) ------- 10 c7c5 3% (395) -- 0.89 -- 62/3/34

r n b q k b . r
p p . . . p p p
. . . . . n . .
. . p . p . . .
. . . p P . . .
. . . . . N N .
P P P P . P P P
R . B Q K B . R



white %                                 engine eval                             log10(depth freq)
 ∧                                       ∧                                       ∧
 │+63                     o              │                          o            │                          ∘
 ┼                 o o  o   o            │+1.1                                   │+48
 │            o  o                       ┼                                       ┼
 │      o o o                            │                                       │
 │-- o------------------- -              │                                       │
 -                                       │                      o                │
 │                                       │                                       │
 │                                       │                                       │
 │                                       │                                       │
 │                                       │                        o              │
 │                                       │                 o                     │
 │                                       │                                       │
 │                                       │                                       │
 │                                      ─│───o────o──────────o──────┼>           │                        ∘
 │                                       ┼0                       12             │
 │                                       │               o                       │
 │+1.3                                   │-0.34 o     o                          │+1                  ∘ ∘
─┼──────────────────────────┼>           ┼          o                           ─┼────────∘─∘─∘─∘─∘─∘───────┼>
 ┼0                       12             │                                       ┼+0.0053                 +1
                           ply                                     ply                                     ply
```

### TODO list:
- [x] Move the first line on the right of the board and format it in a kind of tabula way with label. Something like (but with the correct tabulation:
```
Elapsed time: 1m49s
Ply:                  10 
Move:              c7c5 
Move freq:      3% 
#Games:         395 
EngineEval:     0.89
MoveScore:    62/3/34
```

- [x] Add couple of empty columns on the left of the print string
- [ ] Add (if possibile) the number of "open nodes" still to be investigated
- [x] Generalize the function `align_plots()` to align several multi-line strings (eg. board + info)
